### ISSUE TITLE
초기 환경 설정

### ISSUE THREAD

**Issue by jinlee1703** [SWM-REPL/gifthub-iac#1]
## Description

프로젝트 설정을 위한 초기 환경 설정

## Task

- [x] Issue Template 작성
- [x] Pull-Request Template 작성
- [x] Conventional Commit을 위한 husky 설정
