### ISSUE TITLE
개발 환경 DB 인스턴스 생성

### ISSUE THREAD

**Issue by jinlee1703** [SWM-REPL/gifthub-iac#10]
## Description

서비스를 운영하기 위한 DB (AWS에서는 RDS가 있으나, NCloud Terraform에서는 RDS와 같은 PaaS가 존재하지 않음) 인스턴스 생성

## Task

- [x] DB Instance (Server)
- [x] ACG & ACG-rule
- [x] NIC
- [x] Private Key & root password
