### ISSUE TITLE
Provider 변경 (AWS)

### ISSUE THREAD

**Issue by jinlee1703** [SWM-REPL/gifthub-iac#12]
## Description

&nbsp; NCP에서 제공하지 않는 서비스(CDN, S3 등)로 인해 Provider 변경을 결정하였음

## Task

- [x] 기존 레거시 코드 삭제
- [x] AWS Provider 설정 추가
- [x] AWS Architecture 설계 및 README 추가
