### ISSUE TITLE
AWS VPC 네트워크 구축

### ISSUE THREAD

**Issue by jinlee1703** [SWM-REPL/gifthub-iac#14]
## Description

AWS VPC 환경을 구축하기 위한 관련 작업 수행

## Task

- [x] modules 디렉토리 구축 및 networking 모듈 정의
- [x] environments 디렉토리 구축 및 prod 환경 선언
- [x] prod 환경의 network 설정 관련 리소스 생성
