### ISSUE TITLE
개발 환경 Bastion 인스턴스 생성

### ISSUE THREAD

**Issue by jinlee1703** [SWM-REPL/gifthub-iac#6]
## Description

서비스를 운영하기 위한 Bastion (AWS에서는 EC2) 인스턴스 생성

## Task

- [x] Bastion Instance (Server)
- [x] ACG & ACG-rule
- [x] NIC
- [x] Private Key & root password
- [x] Public IP
