### ISSUE TITLE
개발 환경 WAS 인스턴스 생성

### ISSUE THREAD

**Issue by jinlee1703** [SWM-REPL/gifthub-iac#8]
## Description

서비스를 운영하기 위한 WAS (AWS에서는 EC2) 인스턴스 생성

## Task

- [x] WAS Instance (Server)
- [x] ACG & ACG-rule
- [x] NIC
- [x] Private Key & root password
- [x] OVPN
